apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: simplepods.slinky.dev
spec:
  group: slinky.dev
  names:
    kind: SimplePod
    listKind: SimplePodList
    plural: simplepods
    singular: simplepod
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true